apiVersion: v1
kind: Service

metadata:
   name: color-api-clusterip
   labels:
   app: color-api

spec:
   type: ClusterIP
   selector:
       app: color-api
   ports:
   - port: 80
     targetPort: 80
     protocol: TCP

# kubectl logs -f traffic-generator(pod)
# kubectl delete --force -f traffic-generator.yaml
